config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, :controllers => {:registrations => "registrations" }
  get 'dashboard/admin_dashboard'
  get 'dashboard/user_dashboard'
  get 'list/user_list' 
  get 'list/assign_points/:id' => 'list#assign_points', as: :user_assign_points
  put 'list/update/:id' => 'list#update', as: :user_update_points
  get 'employee/employ' => 'employee#employ', as: :employee_detail
  get 'list/login' => 'list#login' , as: :login
  delete 'list/destroy/:id' => 'list#destroy', as: :user_delete
  post 'list/import' => 'list#import', as: :import_users
  get 'list/impersonate' => 'list#impersonate', as: :impersonate
  get 'list/stop_impersonate' =>'list#stop_impersonate', as: :stop_impersonate
   root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_attached_file :image , :styles => { large:  "600x600>",medium: "300x300>", thumb: "50x50#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  default_scope {where(is_deleted: false)}


def staff?
  true
end

def to_s
  email
end 


  def self.search(search)
    if search
      where("email LIKE ?","%" + search + "%")
    else
      all
    end
  end


  def self.to_csv
    attributes = %w{id  email points doj}

    CSV.generate do |csv|
      csv << attributes

      all.order(doj: :desc).each do |user|
        csv << user.attributes.values_at(*attributes)
      end
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # User.create! row.to_hash
     user = find_by_id(row["id"]) || new
     user.attributes =  row.to_hash#.slice(*accessible_attributes)
     user.save!
     end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
   #impersonates :user





  def after_sign_in_path_for(resource)
   if resource == @admin
      dashboard_admin_dashboard_path
   else 
      employee_detail_path
   end
  end

  def after_sign_out_path_for(resource_or_scope)
      root_path
  end

  # def after_sign_up_path_for(resource)
  #   '/dashboard/admin_dashboard' # Or :prefix_to_your_route
  # end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:points, :doj])
  end

  # def after_sign_up_path_for(resource)
  #   '/dashboard/admin_dashboard' # Or :prefix_to_your_route
  # end
end

  # def after_sign_up_path_for(resource)
  #   puts "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  #   puts resource
  #   if resource == @user
  #     list_user_list_path
  #   else
  #     super
  #   end
  # end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!, only: [:admin_dashboard]
  before_action :authenticate_user!, only: [:user_dashboard]
  # def user_dashboard
  #   if current_user.class == Admin
  #     sign_out_and_redirect(current_user)
  #   end
  # end

  def admin_dashboard
    if current_user.class == User
      sign_out_and_redirect(current_user)
    end
  end
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def employ

    @emp= current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def start_impersonate
    user = User.find_by(id: params[:user_id])
    impersonate_user(user) if user.present?
    redirect_to employee_detail_path
  end
  def stop_impersonating
    stop_impersonating_user
    redirect_to list_user_list_path
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :authenticate_admin!, only: [:user_list]

  def user_list
    @users = User.all#search(params[:search]).paginate(page: params[:page], per_page: 5)
   puts session.id
  #User.find(session[:user_id])
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv }
    end
  end

  def assign_points
    @users = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.email = params[:email]
    @user.points = @user.points.to_i + params[:points].to_i
    @user.doj = Date.parse(params[:doj])
    if @user.valid?
      @user.save
      TestMailer.aprisal(@user).deliver
      redirect_to list_user_list_path
    end
  end

  def destroy
    user = User.find(params[:id])
    user.is_deleted = true
    user.save
    redirect_to list_user_list_path
  end

  def import
    User.import(params[:file])
    redirect_to list_user_list_path, notice: "Products imported."
  end

  def impersonate
    @user=User.find(params[:user_id])
    warden = env['warden']
if warden.authenticated?(:admin)
  warden.authenticated?(:user) && warden.logout(:user)
  # redirect_to warden.session(:admin)[:redirect_back] = "/dashboard/admin_dashboard"
    # warden.session(:user)[:redirect_back] = "/employee/employ"

  warden.set_user(@user, scope: :user)
  redirect_to employee_detail_path 
end



    # session[:current_user_id] = params[:user_id]
    # # User.find(session[:current_user_id])
    # redirect_to dashboard_user_dashboard_path
  end
  def stop_impersonate
    warden = env['warden']
warden.authenticated?(:admin) && warden.authenticated?(:user) # activate both sessions
warden.logout(:user) # log out only the user session, and only the user session data is cleared.

redirect_to warden.session(:admin)[:redirect_back] || "/list/user_list"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, 
    :password_confirmation, :image)
  end

  def account_update_params
    puts '---------------------------------------------'
    params.require(:user).permit(:name, :phone, :email, :image, 
    :password, :password_confirmation, :current_password, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<div class="col-md-3  ml">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-sm" %><br />
  <% end %>
</div>
<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/dashboard/admin_dashboard.html.erb
<h1 style="text-align:center"> Admin Dashboard </h1>


<div class=" row m1 ">
  <div class="col-md-1"></div>
  <div class="col-md-2">
    <%= link_to 'users list' , list_user_list_path ,class: "btn btn-xs btn-success"%>
  </div>
</div>
<div class=" row m1 ">
  <div class="col-md-1"></div>
  <div class="col-md-2">
    <%= link_to 'User Sign_up' , new_user_registration_path ,class: "btn btn-xs btn-success"%>
  </div>
</div>
<div class = " row m1">
  <div class="col-md-1"></div>
  <div class="col-md-2">
    <%= link_to 'Admin logout', destroy_admin_session_path, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-xs btn-danger" %>
  </div>
</div>

app/views/dashboard/user_dashboard.html.erb
<div class="heading"><h1 style="text-align:center;"> User Dashboard </h1>

  <div class = " row m1">
  <div class="col-md-1"></div>
  <div class="col-md-2">


  <%= link_to 'User logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-xs btn-success"  %>

</div>
</div>
<br>

<div class=" row m1 ">
  <div class="col-md-1"></div>
  <div class="col-md-2">
  <%= link_to 'Info', employee_detail_path, class: "btn btn-xs btn-success" %>
</div>
</div>
</div>

app/views/employee/employ.html.erb
<div class="heading"><h1 style="text-align:center"> User Details </h1>




<%= image_tag @emp.image.url(:thumb) %>

<table class="table table-striped">
  <thead>
    <tr>

      <th>UserName</th>

      <th>Points</th>
      
    </tr>





  </thead>

  <tbody>
    
      <tr>
        <td ><%= @emp.email %></td>
       
        <td  ><%= @emp.points %></td>

        <td class="col-md-1"><%= link_to 'redeem points', "https://www.flipkart.com",class: "btn btn-xs btn-danger"%></td>

               
      </tr>
    
  </tbody>
</table>
<div class="col-md-2 ml">
  <%= link_to 'User logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-xs btn-danger" %>
</div>
</br>
<div class="col-md-2 ml">
<% if warden.authenticated?(:admin) && warden.authenticated?(:user) %>
<%= link_to 'stop impersonate',stop_impersonate_path,class: "btn btn-xs btn-danger" %>
<% end %>
</div>
</div>

app/views/home/index.html.erb
<div class="heading "><h1 style="text-align:center">Oraange application </h1></div>

<!-- <div class="col-md-4"></div>
<div class="flex-container">

<div class="row">
<div class="column" style="background-color:#aaa;">
<div class = " row m1 ">
  <div class="col-md-1"></div>
  
 <div class="flex-child magenta">

  <div class="col-md-2">
 -->



<div class='row no-gutters'>
  <div class="col-md-6 no-gutters">
    <div class="leftside d-flex justify-content-center align-items-center ">
      <%= link_to image_tag('admin-settings-male.png'), new_admin_session_path  %>
    <%#= image_tag "admin-settings-male.png"%><br>
    <%= link_to 'Admin Login', new_admin_session_path ,class: " ls"%>
  </div>
</div>

<!--   </div>
</div>
</div>
</div>

 <div class="column" style="background-color:#bbb;">
<div class=" row m1 ">
  <div class="col-md-1"></div>
    

  <div class="col-md-2"> -->

    

<div class="col-md-6 no-gutters">
    <div class="rightside d-flex justify-content-center align-items-center">
    <%= link_to image_tag("user.png"), new_user_session_path %><br>
    <%= link_to 'Employee Login', new_user_session_path,class: " ls"%>
</div>
</div>
</div>





<!--       </div>
</div>

</div>
</div>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oraange</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/list/assign_points.html.erb
<h1 style="text-align:center">User Update Form </h1>
<div class="paddingBetweenCols b1">
  <%= form_tag user_update_points_path, method: 'put' do %>
      <div class="row">
        <p class="paddingBetweenCols">User Id/Email:</p>
        <div class="col-md-4">
             <%= text_field_tag :email, @users.email , placeholder: "Email", autofocus: true ,class: "form-control search-box input-lg" %>
        </div>
      </div>
      <div class="row m1">
        <p class="paddingBetweenCols">POINTS:</p>
        <div class="col-md-4">
           <%= number_field_tag :points, @users.points , placeholder: "Points", autofocus: true ,class: "form-control search-box input-lg" %>
        </div>
      </div>
      <div class="row m1">
        <p class="paddingBetweenCols">Date Of Join:</p>
        <div class="col-md-4">
         <%= date_field_tag :doj, @users.doj , placeholder: "Date of join", autofocus: true ,class: "form-control search-box input-lg" %>
        </div>
      </div>
      <div class= "row m1 m2">
        <div class="col-md-2">
          <%= button_tag(type: :submit, class: "btn btn-primary btn-success") do %>
            <i class="fa fa-search"></i> Update
          <% end %>
        </div>
      </div>
    <% end %>
</div>
<br>
<div class="col-md-2">
<%= link_to 'Back',list_user_list_path ,class: "btn btn-xs btn-success"%>
</div>

app/views/list/login.html.erb
<!DOCTYPE html>
<html lang="en-IN">
<head>
<meta charset="utf-8">
<title></title>


</head>
<body>
<div id="login-form">

<input type="radio" checked id="login" name="switch" class="hide">
<input type="radio" id="signup" name="switch" class="hide">

<div>
<ul class="form-header">
<li><label for="login"><i class="fa fa-lock"></i> LOGIN<label for="login"></li>
<li><label for="signup"><i class="fa fa-credit-card"></i> REGISTER</label></li>
</ul>
</div>

<div class="section-out">
<section class="login-section">
<div class="login">
<form action="">
<ul class="ul-list">
<li><input type="email" required class="input" placeholder="Your Email"/><span class="icon"><i class="fa fa-user"></i></span></li>
<li><input type="password" required class="input" placeholder="Password"/><span class="icon"><i class="fa fa-lock"></i></span></li>
<li><span class="remember"><input type="checkbox" id="check"> <label for="check">Remember Me</label></span><span class="remember"><a href="">Forget Password</a></span></li>
<li><input type="submit" value="SIGN IN" class="btn"></li>
</ul>
</form>
</div>

<div class="social-login">Or sign in with &nbsp;
<a href="" class="fb"><i class="fa fa-facebook"></i></a>
<a href="" class="tw"><i class="fa fa-twitter"></i></a>
<a href="" class="gp"><i class="fa fa-google-plus"></i></a>
<a href="" class="in"><i class="fa fa-linkedin"></i></a>
</div>
</section>

<section class="signup-section">
<div class="login">
<form action="">
<ul class="ul-list">
<li><input type="email" required class="input" placeholder="Your Email"/><span class="icon"><i class="fa fa-user"></i></span></li>
<li><input type="password" required class="input" placeholder="Password"/><span class="icon"><i class="fa fa-lock"></i></span></li>
<li><input type="checkbox" id="check1"> <label for="check1">I accept terms and conditions</label></li>
<li><input type="submit" value="SIGN UP" class="btn"></li>
</ul>
</form>
</div>

<div class="social-login">Or sign up with &nbsp;
<a href="" class="fb"><i class="fa fa-facebook"></i></a>
<a href="" class="tw"><i class="fa fa-twitter"></i></a>
<a href="" class="gp"><i class="fa fa-google-plus"></i></a>
<a href="" class="in"><i class="fa fa-linkedin"></i></a>
</div>
</section>
</div>

</div>

</body>
</html>

app/views/list/user_list.html.erb
<!-- 
<h1 style="text-align:center;">Listing Employees</h1>
<div >
 <%#= form_tag list_user_list_path, :method => 'get' do %>
    <div class="form-group row left-padding col-md-12">
      <div class="col-md-10">
       <%#= text_field_tag :search, params[:search], placeholder: "Search User", autofocus: true ,class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
      <%#= button_tag(type: :submit, class: "btn btn-primary btn-success") do %>
          <i class="fa fa-search"></i> Search User
        <%# end %>
      </div>
    </div>
<%# end %>
</div>
 -->
<!-- <table class="table table-sm table-hover table-striped "> -->
<!--   <%# if current_user.staff? %>
    <li><%#= link_to 'Impersonate', '/impersonate' %></li>
  <%# end %> -->
<table id="example" class="display">
  <thead>
    <tr>
        <th colspan="3" class="page-header">
          <h2>Employees</h2>
        </th>
      </tr>
    <tr>
      <th >UserName</th>
      <th >Points</th>
      <th >DOJ</th>
      <th> Edit</th>
      <th> Delete</th>

      
    </tr>
  </thead>

  <tbody id="list">
    <% @users.each do |user| %>
      <tr>
        <td ><%= user.email %></td>
        <td ><%= user.points %></td>
        <td ><%= user.doj %></td>


        <td class = "col-md-1"><%= link_to 'update', user_assign_points_path(user.id), class: "btn btn-xs" %></td>

        <td class="col-md-1"><%= link_to 'Delete', user_delete_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger"  %></td>
        <td><%=link_to "Impersonate", impersonate_path(user_id: user.id)%></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
            <tr>
                <th >UserName</th>
                <th >Points</th>
                <th >DOJ</th>
            </tr>
        </tfoot>
</table>
<%#= will_paginate @users %><br>
</div>
<div class="col-md-2">
<%= link_to 'Admin Homepage', dashboard_admin_dashboard_path, class: "btn btn-xs btn-success" %>
</div>
<div class="col-md-2">
<%= link_to 'create/add user ' , new_user_registration_path , class: "btn btn-xs btn-success" %>
</div>
<div class="col-md-2">
<%= link_to 'Download Users', list_user_list_path(format: "csv"), class: "btn btn-default" %>
</div>
<br>

<h2>Import Users</h2>

<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/user_impersonate/_header.html.erb
<style>
#impersonating {
  width: 100%;
  margin: 0;
  padding: 12px 0;
  background: #c70000;
  border-bottom: 1px solid black;
  line-height: 1.9;
  font-size: 12px;
  font-family: "Lucida Sans Unicode","Lucida Grande",Verdana,Arial,Helvetica,sans-serif;
}
#impersonating .impersonate-controls {
  color: white;
  font-weight: normal;
  font-size: 15px;
  max-width: 960px;
  margin-left: auto;
  margin-right: auto;
}
#impersonating .impersonate-controls .impersonate-info {
  margin-bottom: 6px;
  padding-bottom: 2px;
  border-bottom: 1px solid #dd0000;
}
#impersonating .impersonate-controls form {
  display: inline;
  margin-right: 16px;
}
#impersonating .impersonate-controls .revert-form {
  margin-left: 16px;
}
#impersonating .impersonate-controls select {
  background: white;
}
#impersonating .impersonate-controls .admin_name, #impersonating .impersonate-controls .user_name, #impersonating .impersonate-controls .user_id, #impersonating .impersonate-controls .account_id {
  font-weight: bold;
}
#impersonating .impersonate-controls a {
  text-decoration: underline;
  color: white;
}
</style>
<div id="impersonating">
  <div class="impersonate-controls">
    <div class="impersonate-info">
      You (
      <span class="admin_name"><%= current_staff_user %></span>
      ) are impersonating
      <span class="admin_name"><%= current_staff %></span>
      ( User id: <%= current_staff.to_param %> )
    </div>

    <div class="impersonate-buttons">
      <%= form_tag impersonate_engine.revert_impersonate_user_url,
          :method => :delete, :class => 'revert-form' do %>
        <button type = "submit"> Revert to admin</button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>